### ISSUE TITLE
inpaint background broken in A1111 v1.10 - "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by CounterfeitMonk** [PladsElsker/sd-webui-inpaint-background#14]
I've lost the ability to use this extension. First, the tab has been moved under the "Batch" tab, and second, when I try to generate an image, I get an instant `IndexError: tuple index out of range`.

![2024-08-02 15_43_20-Stable Diffusion — Mozilla Firefox](https://github.com/user-attachments/assets/1f57e782-57ff-453c-ae84-bdfb9d7ca833)

![2024-08-02 15_44_07-Stable Diffusion — Mozilla Firefox](https://github.com/user-attachments/assets/b816496a-3626-42c2-a755-253bcb523216)

**Comment by PladsElsker** [comment]
Thank you for reporting. 
1.10 just released, things broke. I'll investigate and hopefully find a fix that will be stable for a couple more releases. 

I think all the extensions that use sdwi2iextender library are broken at the moment.
