### ISSUE TITLE
The tab is empty

### ISSUE THREAD

**Issue by ovchvi** [PladsElsker/sd-webui-inpaint-background#16]
I installed the extension according to the instructions, however, after switching to the Inpaint background tab in img2img, I saw that it was completely empty. The screenshot is attached below. What should I do?
![Screenshot 2024-08-04 154756](https://github.com/user-attachments/assets/32abd7da-899c-454d-8f03-2419d0875f9f)

**Comment by PladsElsker** [comment]
Update Webui to `1.10-RC`. You are on `1.8-RC`.
