### ISSUE TITLE
Error using img2img!

### ISSUE THREAD

**Issue by rafaelfabres** [PladsElsker/sd-webui-inpaint-background#17]
After the last update of the extension, this error started to appear when using img2img: 

![image](https://github.com/user-attachments/assets/c72f0742-1d4f-4f30-9e71-fa1efb761246)

after uninstalling the extension everything went back to normal...

**Comment by PladsElsker** [comment]
What version of the Webui are you using? And is the extension displayed properly in the UI?

**Comment by rafaelfabres** [comment]
> What version of the Webui are you using? And is the extension displayed properly in the UI?
Version 1.10.1, The extension worked fine, but when using img2img or inpaint this error occurred

**Comment by PladsElsker** [comment]
Thank you, I will fix this asap.

**Comment by PladsElsker** [comment]
Should be fixed now.

**Comment by rafaelfabres** [comment]
thanks!!
